### ISSUE TITLE
Mod incompatibility (i think) crashes server.

### ISSUE THREAD

**Issue by LEPA4** [BeardlessBrady/Currency-Mod#140]
https://hastebin.com/icomewokop.rb
I'm 99.9% sure that the incompatibility is with minecolonies. But. the hastebin above shows the crash report. If I disable minecolonies from the modlist it works. ill run a few more test and get back if I can fix issue. but idk.

**Comment by Beardlessbrady** [comment]
Something to do with me enchanting the creative block. In the next update I will differentiate the creative block through texture. I will leave this issue here till then to ensure the issue is fixed.

**Comment by LEPA4** [comment]
https://hastebin.com/atuwarovac.rb
still crashes after update
